import { Geist, Geist_Mono, Jockey_One } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Module 7 - Next.js Forms",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
